In [1]:
#jawaban nomer 1
tinggi = [180, 215, 210, 210, 188, 176, 209, 200] # dalam cm 

# Import numpy dengan alias np
import numpy as np

# Buat numpy array dengan list tinggi beri nama variabel np_tinggi
np_tinggi = np.array(tinggi)


# Print tipe data np_baseball
print(type(np_tinggi))
print(np_tinggi)


<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


In [3]:
#jawaban nomer 2
# Buat np_tinggi menjadi dalam satuan meter
np_tinggi = np.divide(np_tinggi,100)

# print np_tinggi
print(np_tinggi)

[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]


In [4]:
#jawaban nomer 3
berat = [88.5, 100, 98, 101, 78.3, 65.3, 109, 110]

# Buatlah numpy array dari list berat dan simpan dalam np_berat
np_berat = np.array(berat)

# hitung bmi dari berat dan tinggi simpan ke dalam variabel bmi
bmi = np.divide(np_berat, np_tinggi)
print(bmi)

[49.16666667 46.51162791 46.66666667 48.0952381  41.64893617 37.10227273
 52.15311005 55.        ]


In [5]:
#jawaban nomer 4
# Simpan dalam variabel bmi_tinggi
bmi_tinggi = bmi > 23
print(bmi_tinggi)

# Partisi numpy array bmi dengan menggunkan bmi_tinggi untuk mencari bmi yang hanya lebih besar dari 23
print(bmi[bmi_tinggi])

[ True  True  True  True  True  True  True  True]
[49.16666667 46.51162791 46.66666667 48.0952381  41.64893617 37.10227273
 52.15311005 55.        ]


In [7]:
#jawaban nomer 5
print ("A")

A


In [8]:
#jawaban nomer 6
# print hasil np_berat yang melik index terakhir
print(np_berat[:-1])

[ 88.5 100.   98.  101.   78.3  65.3 109. ]


In [9]:
#jawaban nomer 7
pemain_basket = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

# Buatlah 2D array dari pemain_basket simpan dalam variabel basket_2d
basket_2d = np.array(pemain_basket)

# print tipe dari basket_2d
print(type(basket_2d))

# print basket_2d
print(basket_2d)

# print dimensi dari basket_2d dengan basket_2d.shape
print(basket_2d.shape)

<class 'numpy.ndarray'>
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
(4, 2)


In [10]:
#jawaban nomer 8
# Gunakan slicing untuk untuk mengambil hanya kolom pertama dari basket_2d
print(basket_2d[:,0])


# Gunakan slicing untuk mendapatkan 2 baris terakhir dan hanya kolom kedua dari basket_2d
print(basket_2d[-2:,1])

[180. 215. 210. 188.]
[98.5 75.2]


In [11]:
#jawaban nomer 9
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [12]:
# Print dengan tambahkan berat dari basket_2d (kolom kedua) dengan 5 
print(np.add(basket_2d[:,1],5))

# Print dengan mengubah tinggi basket_2d (kolom pertama) yang awalnya satuannya cm menjadi m
print(np.divide(basket_2d[:,0],100))

[ 83.4 107.7 103.5  80.2]
[1.8  2.15 2.1  1.88]


In [14]:
#jawaban nomer 10
# Berapakah mean dari np_tinggi? Kemudian print
print(np.mean(np_tinggi))

# Berapakah median dari np_tinggi? Kemudian print
print(np.median(np_tinggi))

1.9849999999999999
2.045


In [15]:
#jawaban nomer 11
# Print tinggi dari basket_2d (kolom pertama)
rata_rata = np.mean(basket_2d[:,0])
print("Rata - Rata: " + str(rata_rata) )

# Print median dari tinggi basket_2d
med = np.median(basket_2d)
print("Median: " + str(med))

# Print standar deviasi dari basket_2d
stddev = np.std(basket_2d)
print("Standard Deviation: " + str(stddev))

# Print korelasi antara kolom pertama dengan kedua dari basket_2d
korelasi = np.corrcoef(basket_2d[:,[0,1]])
print("Korealasi: " + str(korelasi))

Rata - Rata: 198.25
Median: 141.35
Standard Deviation: 56.390973346804365
Korealasi: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
